# version: '3.8'

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb:hgu
    volumes:
      - mariaDB_volume:/var/lib/mysql
    networks:
      - wordpress_net
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WD_NAME: ${WD_NAME}
      WD_AD: ${WD_AD}
      WD_AD_PASS: ${WD_AD_PASS}
      DB_INIT_FLAG: ${DB_INIT_FLAG}
    expose:
      - "3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress:hgu
    volumes:
      - wordpress_volume:/wordpress
    networks:
      - wordpress_net
    environment:
      WD_NAME: ${WD_NAME}
      WD_AD: ${WD_AD}
      WD_AD_PASS: ${WD_AD_PASS}
      DB_HOST: ${DB_HOST}
      WD_USER: ${WD_USER}
      WD_USER_EMAIL: ${WD_USER_EMAIL}
      WD_USER_PASS: ${WD_USER_PASS}
      WD_INIT_FLAG: ${WD_INIT_FLAG}
    restart: always
    healthcheck:
          test: ["CMD-SHELL", "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect localhost:9000"]
          interval: 10s
          timeout: 10s
          retries: 3
          start_period: 30s
    expose:
      - "9000"  
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx:hgu
    networks:
      - wordpress_net
    ports:
      - "443:443"
    environment:
      NGINX_INIT_FLAG: ${NGINX_INIT_FLAG}
    volumes:
      - wordpress_volume:/wordpress
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy

# volume
volumes:
  mariaDB_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hgu/data/DB
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hgu/data/wordpress

networks:
  wordpress_net:
    driver: bridge
