version: '3.8'

services: #여기에 사용할 컨테이너(어플리케이션)을 정의
  mariadb:
    build: ./mariadb #mariadb폴더속 dockerfile로 이미지빌드
    container_name: mariadb
    volumes:
      - mariaDB_volume:/var/lib/mysql #여기만 bind하면 되나?
    networks:
      - wordpress_net
    ports: #포트를 외부에 노출해야하나? 굳이?
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - /home/hgu/data/WordPress:/wordpress
    networks:
      - wordpress_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "CMD-SHELL", "curl -f localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports: #포트를 외부에 노출해야하나? 굳이?
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - wordpress_net
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/wordpress
    restart: always
    healthcheck:
      test: ["CMD-SHELL", " curl -f localhost ping --silent || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      wordpress:
        condition: service_healthy

# volume
volumes:
  mariaDB_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hgu/data/DB
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hgu/data/wordpress

networks:
  wordpress_net:
    driver: bridge
