FROM alpine:3.19

#필요한 패키지 설치
RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add mariadb mariadb-client

COPY mariaDB.sh /usr/local/bin

RUN chmod +x /usr/local/bin/mariaDB.sh

#DB포트 접근 허용
EXPOSE 3306

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/mariaDB.sh"]

