FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add dumb-init && \
    apk add php php-phar php-curl php-openssl php-mysqli php-iconv php-fpm fcgi

COPY wordpress.sh /usr/local/bin
COPY www.conf /
COPY php-fpm.conf /

RUN chmod +x /usr/local/bin/wordpress.sh

EXPOSE 9000

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/wordpress.sh"]
