FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add nginx && \
    apk add openssl

RUN mkdir -p /etc/nginx/ssl

COPY nginx.sh /usr/local/bin

COPY default.conf /etc/nginx/http.d/default.conf
# COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /usr/local/bin/nginx.sh

EXPOSE 80

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/nginx.sh"]
