FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add nginx

COPY nginx.sh /usr/local/bin

RUN chmod +x /usr/local/bin/nginx.sh

EXPOSE 80

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/nginx.sh"]
