FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add nginx && \
    apk add openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj ""

COPY nginx.sh /usr/local/bin
COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /usr/local/bin/nginx.sh

EXPOSE 80

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/nginx.sh"]
