FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add nginx && \
    apk add openssl

RUN mkdir -p /etc/nginx/ssl

# keyout: 생성된 private키를 저장하는 경로, out: 생성된 인증서를 저장하는 경로, subj: 인증서의 주체에 대한 정보
# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#     -keyout /etc/ssl/private/nginx-selfsigned.key \
#     -out /etc/ssl/certs/nginx-selfsigned.crt \
#     -subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=Cardet/CN=hgu.com"

COPY nginx.sh /usr/local/bin
COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /usr/local/bin/nginx.sh

EXPOSE 80

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/nginx.sh"]
