FROM alpine:3.19

#필요한 패키지 설치
RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init mariadb mariadb-client

#실제 mariaDB의 데이터 디렉토리를 초기화하고, MariaDB가 작동할 수 있도록 하는 초기화 작업
#해당경로에 mysql폴더가 존재하는지 확인하고 폴더를 생성하는 쉘 스크립트를 작성해야한다
COPY mariaDB.sh /usr/local/bin
RUN chmod +x /usr/local/bin/mariaDB.sh

#DB포트 접근 허용
EXPOSE 3306

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/mariaDB.sh"]

