FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init && \
    apk add php php-phar php-curl php-openssl php-mysqli php-iconv php-fpm

COPY wordpress.sh /usr/local/bin

RUN chmod +x /usr/local/bin/wordpress.sh

EXPOSE 9000

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/wordpress.sh"]
