FROM alpine:3.19

RUN apk update && \
    apk upgrade && \
    apk add dumb-init && \
    apk add php php-phar php-curl php-openssl php-mysqli php-iconv php-fpm php-opcache php-gd php-zlib php-json php-mbstring && \
    apk add php-xml php-simplexml && \
    apk add fcgi

COPY wordpress.sh /usr/local/bin
COPY www.conf /etc/php82/php-fpm.d/
COPY php-fpm.conf /etc/php82/

RUN chmod +x /usr/local/bin/wordpress.sh

EXPOSE 9000

#기본 명령어 설정
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/wordpress.sh"]
